# Runs edgetest to manage dependency upgrades
#
# Public actions used:
#   - https://github.com/actions/checkout
#   - https://github.com/actions/setup-python
#   - https://github.com/edgetest-dev/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '0 10 * * 1-5'
  workflow_dispatch:

jobs:
  edgetest:
    name: Run edgetest
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - name: Set up Python 3.12
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
      with:
        python-version: 3.12
    - id: run-edgetest
      name: Run edgetest
      uses: edgetest-dev/run-edgetest-action@8ceeac94abe951d6b51305454bc6d0ff2096e2ec  # v1.7.0
      with:
        base-branch: 'main'
        edgetest-flags: '-c pyproject.toml --export'
        python-version: 3.12
        skip-pr: 'false'
