# Validates that the PR title follows the conventional commits format, i.e.:
#
#   feat: add S3 backend repository (#100)
#   |     |__________ subject
#   |________________ type
#
#   ops(edgetest): changes by run-edgetest action (#101)
#   |  |           |__ subject
#   |  |______________ scope (optional)
#   |_________________ type
#
# Public actions used:
#   - https://github.com/actions/checkout
#   - https://github.com/amannn/action-semantic-pull-request

name: Validate PR title

on:
  pull_request:  # runs against `main` and integration branches
    branches: ['main', '**/integration/**']
    type:  # runs when PRs are opened or their titles are edited
      - edited
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        requireScope: false
        types: |  # allows all types - listed for clarity
          build
          chore
          docs
          feat
          fix
          ops
          perf
          refactor
          revert
          style
          test
